update Jenkinfile backend

diff --git a/backend/Jenkinsfile b/backend/Jenkinsfile
--- a/backend/Jenkinsfile
+++ b/backend/Jenkinsfile
@@ -116,64 +116,86 @@ spec:
                 }
             }
         }
-        // stage('Code Analysis') {
-        //     parallel {
-        //         stage('SonarQube Scan') {
-        //             environment {
-        //                 SONAR_AUTH_TOKEN = credentials('sonarqube-token')
-        //                 SCANNER_HOME = tool 'sonarqube'
-        //             }
-        //             steps {
-        //                 container('node') {
-        //                     dir('backend'){
-        //                         withSonarQubeEnv(installationName: 'sonarqube') {
-        //                             sh '''
-        //                                 $SCANNER_HOME/bin/sonar-scanner \
-        //                                 -Dsonar.projectKey=smash-shop-backend-project \
-        //                                 -Dsonar.host.url=http://192.168.88.133:31000/ \
-        //                                 -Dsonar.login=$SONAR_AUTH_TOKEN
-        //                             '''
-        //                         }
-        //                     }
-        //                 }
-        //             }
-        //         }
-        //         stage('Trivy Source Scan') {
-        //             steps {
-        //                 container('trivy') {
-        //                     dir('backend') {
-        //                         sh '''
-        //                             trivy fs --no-progress --severity MEDIUM,HIGH,CRITICAL \
-        //                             --scanners vuln,secret \
-        //                             --format table . > trivy-source.txt 2>&1
-        //                             cat trivy-source.txt
-        //                         '''
-        //                         sh '''
-        //                             CRITICAL_COUNT=$(grep -oP 'CRITICAL: \\K[0-9]+' trivy-source.txt | head -1)
-        //                             if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
-        //                                 echo "❌ Critical vulnerabilities found in source scan ($CRITICAL_COUNT), failing pipeline"
-        //                                 exit 1
-        //                             else
-        //                                 echo "✅ No critical vulnerabilities found."
-        //                             fi
-        //                         '''
-        //                     }
-        //                 }
-        //             }
-        //         }
-        //     }
-        // }
-        // stage('Quality Gate') {
-        //     steps {
-        //         container('node') {
-        //             dir('backend'){
-        //                 timeout(activity: true, time: 2, unit: 'MINUTES') {
-        //                     waitForQualityGate abortPipeline: true, credentialsId: 'sonarqube-token'
-        //                 }
-        //             }
-        //         }
-        //     }
-        // }
+        stage('Code Analysis') {
+            parallel {
+                // stage('SonarQube Scan') {
+                //     environment {
+                //         SONAR_AUTH_TOKEN = credentials('sonarqube-token')
+                //         SCANNER_HOME = tool 'sonarqube'
+                //     }
+                //     steps {
+                //         container('node') {
+                //             dir('backend'){
+                //                 withSonarQubeEnv(installationName: 'sonarqube') {
+                //                     sh '''
+                //                         $SCANNER_HOME/bin/sonar-scanner \
+                //                         -Dsonar.projectKey=smash-shop-backend-project \
+                //                         -Dsonar.host.url=http://192.168.88.133:31000/ \
+                //                         -Dsonar.login=$SONAR_AUTH_TOKEN
+                //                     '''
+                //                 }
+                //             }
+                //         }
+                //     }
+                // }
+                stage('SonarQube Scan') {
+                    steps {
+                        // Thêm retry để nếu timeout do mạng thì sẽ thử lại
+                        retry(2) {
+                            container('node') {
+                                script {
+                                    def scannerHome = tool 'sonarqube'
+                                    dir('backend') {
+                                        withSonarQubeEnv(credentialsId: 'sonarqube-token',installationName: 'sonarqube') {
+                                            sh """
+                                                ${scannerHome}/bin/sonar-scanner \
+                                                -Dsonar.projectKey=smash-shop-backend-project \
+                                                -Dsonar.sources=. \
+                                                -Dsonar.host.url=http://192.168.88.133:31000/ \
+                                            """
+                                        }
+                                    }
+                                }
+                            }
+                        }
+                    }
+                }
+                stage('Trivy Source Scan') {
+                    steps {
+                        container('trivy') {
+                            dir('backend') {
+                                sh '''
+                                    trivy fs --no-progress --severity MEDIUM,HIGH,CRITICAL \
+                                    --scanners vuln,secret \
+                                    --format table . > trivy-source.txt 2>&1
+                                    cat trivy-source.txt
+                                '''
+                                sh '''
+                                    CRITICAL_COUNT=$(grep -oP 'CRITICAL: \\K[0-9]+' trivy-source.txt | head -1)
+                                    if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
+                                        echo "❌ Critical vulnerabilities found in source scan ($CRITICAL_COUNT), failing pipeline"
+                                        exit 1
+                                    else
+                                        echo "✅ No critical vulnerabilities found."
+                                    fi
+                                '''
+                            }
+                        }
+                    }
+                }
+            }
+        }
+        stage('Quality Gate') {
+            steps {
+                container('node') {
+                    dir('backend'){
+                        timeout(activity: true, time: 5, unit: 'MINUTES') {
+                            waitForQualityGate abortPipeline: true, credentialsId: 'sonarqube-token'
+                        }
+                    }
+                }
+            }
+        }
 
         stage('Trivy Source Scan') {
             steps {
@@ -235,25 +257,25 @@ spec:
                 }
              }
         }
-        // stage('Update Manifests') {
-        //     steps {
-        //         container('node') {
-        //             withCredentials([string(credentialsId: 'githubtoken', variable: 'GIT_TOKEN')]) {
-        //                 sh '''
-        //                     set -e
-        //                     git clone https://github.com/NHongCuong/smash-shop-k8s-mainfest.git
-        //                     cd smash-shop-k8s-mainfest/k8s-manifests/backend
-        //                     sed -i.bak "s|nhongcuong/smash-shop-backend-image:.*|nhongcuong/smash-shop-backend-image:$IMAGE_TAG|" deployment.yaml
-        //                     git config user.email "nguyenhongcuonga1@gmail.com"
-        //                     git config user.name "NHongCuong"
-        //                     git add deployment.yaml
-        //                     git commit -m "Update image to nhongcuong/smash-shop-backend-image:$IMAGE_TAG"
-        //                     git push https://$GIT_TOKEN@github.com/NHongCuong/smash-shop-k8s-mainfest.git HEAD:main
-        //                 '''
-        //             }
-        //         }
-        //     }
-        // }
+        stage('Update Manifests') {
+            steps {
+                container('node') {
+                    withCredentials([string(credentialsId: 'githubtoken', variable: 'GIT_TOKEN')]) {
+                        sh '''
+                            set -e
+                            git clone https://github.com/NHongCuong/smash-shop-k8s-mainfest.git
+                            cd smash-shop-k8s-mainfest/k8s-manifests/backend
+                            sed -i.bak "s|nhongcuong/smash-shop-backend-image:.*|nhongcuong/smash-shop-backend-image:$IMAGE_TAG|" deployment.yaml
+                            git config user.email "nguyenhongcuonga1@gmail.com"
+                            git config user.name "NHongCuong"
+                            git add deployment.yaml
+                            git commit -m "Update image to nhongcuong/smash-shop-backend-image:$IMAGE_TAG"
+                            git push https://$GIT_TOKEN@github.com/NHongCuong/smash-shop-k8s-mainfest.git HEAD:main
+                        '''
+                    }
+                }
+            }
+        }
         stage('Trigger ArgoCD Sync') {
             steps {
                 container('node') {
